In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0 

11493376/11490434 [==============================] - 4s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.26130337, -0.75574607,  0.19851235, -0.24441311, -0.64442354,
         0.52590317,  0.2070129 , -0.0954557 , -0.12475814, -0.10985133]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.13109948, 0.0474135 , 0.12312073, 0.0790626 , 0.0529967 ,
        0.17081076, 0.12417179, 0.09176192, 0.08911209, 0.09045041]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

1.767199

In [8]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 957us/step - loss: 0.4739 - accuracy: 0.8628
Epoch 2/5
1875/1875 [==============================] - 2s 943us/step - loss: 0.1500 - accuracy: 0.9551
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1066 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 2s 923us/step - loss: 0.0883 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 2s 984us/step - loss: 0.0774 - accuracy: 0.9759


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0785 - accuracy: 0.9766


[0.07845544070005417, 0.9765999913215637]

In [11]:
prob_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [12]:
prob_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.2096655e-08, 1.8285846e-08, 1.8191304e-05, 8.7886401e-06,
        1.9996477e-10, 1.9305131e-07, 1.2902978e-12, 9.9997151e-01,
        4.9461823e-07, 7.5061928e-07],
       [2.2821005e-09, 3.7131071e-05, 9.9994755e-01, 9.0151261e-06,
        4.0780605e-15, 5.2019241e-06, 9.5915959e-07, 1.1686370e-13,
        2.3150482e-08, 7.8118816e-15],
       [1.2140387e-05, 9.9672168e-01, 3.6149213e-04, 1.9102099e-05,
        7.5931646e-05, 2.0817279e-05, 1.7102211e-04, 2.3035817e-03,
        3.1057451e-04, 3.7767206e-06],
       [9.9958414e-01, 1.5172736e-07, 2.3044861e-04, 9.8217788e-07,
        1.4270286e-06, 4.2983929e-06, 1.5224156e-04, 2.7114431e-06,
        5.6204804e-08, 2.3591027e-05],
       [8.3582586e-07, 5.3092137e-08, 1.8804963e-05, 5.2901896e-08,
        9.9766326e-01, 5.1772318e-08, 1.2351817e-05, 3.5639055e-04,
        3.4879661e-06, 1.9447589e-03]], dtype=float32)>